services:
  wisecp:
    image: thecodingmachine/php:8.2-v4-apache
    ports:
      - "8081:80"
    environment:
      - PHP_EXTENSION_MYSQLI=1
      - PHP_EXTENSION_PDO_MYSQL=1
      - PHP_EXTENSION_INTL=1
      - PHP_EXTENSION_GD=1
      - PHP_EXTENSION_BCMATH=1
      - PHP_EXTENSION_ZIP=1
      - PHP_INI_MEMORY_LIMIT=512M
      - PHP_INI_SESSION_SAVE_PATH=/tmp
    volumes:
      - .:/var/www/html
      # Пробрасываем конфиг прямо в Apache
      - ./php-conf/ioncube.ini:/etc/php/8.2/apache2/conf.d/00-ioncube.ini
      - ./php-conf/ioncube.ini:/etc/php/8.2/cli/conf.d/00-ioncube.ini
